### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by brett18618** [jerrytheo/psopy#3]
Hi thank you for your awesome project first, now I meet the following error:
ImportError: cannot import name 'minimize_pso' from 'psopy' (unknown location).

I ran psopy from Git in python 3.7 and I followed the instruction of installation correctly.

**Comment by halil93ibrahim** [comment]
Hi, can you solve this issue?

**Comment by laura-matrajt** [comment]
yeah, I am having the same issue... any chance you will solve this soon?

**Comment by brett18618** [comment]
No, I chose another package in Github.

**Comment by halil93ibrahim** [comment]
Hi,
Which package do you use. Are you suggest?

**Comment by brett18618** [comment]
PySwarms

**Comment by LuberLinder** [comment]
Working example (except that `options` should be kwargs, was found at the package installation path, for me it's `/lib/python3.7/site-packages/psopy/minimize.py`) is:

```python
import numpy as np
from psopy import _minimize_pso
from psopy import init_feasible, gen_confunc


fun = lambda x: (x[0] - 1)**2 + (x[1] - 2.5)**2
fun_ = lambda x: np.apply_along_axis(fun, 1, x)

cons = ({'type': 'ineq', 'fun': lambda x:  x[0] - 2 * x[1] + 2},
        {'type': 'ineq', 'fun': lambda x: -x[0] - 2 * x[1] + 6},
        {'type': 'ineq', 'fun': lambda x: -x[0] + 2 * x[1] + 2},
        {'type': 'ineq', 'fun': lambda x: x[0]},
        {'type': 'ineq', 'fun': lambda x: x[1]})

x0 = init_feasible(cons, low=0., high=2., shape=(1000, 2))
confunc = gen_confunc(cons)

options={'g_rate': 1., 'l_rate': 1., 'max_velocity': 4., 'stable_iter': 50}
res = _minimize_pso(fun_, x0, confunc=confunc, **options)

print(res.x)
```

**Comment by zhxd050946** [comment]
use minimize to replace minimize_pso

**Comment by jerrytheo** [comment]
@zhxd050946 is right. I will update the documentation to reflect this.
